# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # schedule:
  #   - cron: '*/2 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run another one-line script
      run: echo "Hello, world! [${{ secrets.GITHUB_TOKEN }}][$HOME][$BASH_VERSION][${{ secrets.GRUT }}]"

    - name: Docker build & push for test-1
      uses: docker/build-push-action@v1
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          path: image1
          repository: gissehel/test-1
          tag_with_ref: true
          tag_with_sha: true
          add_git_labels: true    

    - name: Docker build & push for test-2
      uses: docker/build-push-action@v1
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          path: image2
          repository: gissehel/test-2
          tag_with_ref: true
          tag_with_sha: true
          add_git_labels: true    
          
