# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '*/2 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run another one-line script
      run: echo "Hello, world! [${{ secrets.GITHUB_TOKEN }}][$HOME][$BASH_VERSION][${{ secrets.GRUT }}]"

